version: '3'

services:
        otp:
                container_name: otp-ba
                image: opentripplanner-ba:02
                build: .
                command: java -Xmx16G -jar /var/otp/otp-1.5.0-SNAPSHOT-shaded.jar --router buenosaires --graphs /var/otp/graphs --server
                ports:
                        - 8080:8080
