version: '3.7'

services:       

        postgres:
                image: "postgres:10"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_DB=onebusaway
                        - POSTGRES_HOST_AUTH_METHOD=trust
                ports:               
                # psql postgres://postgres@localhost:5433/onebusaway
                        - "5433:5432"                        
        build-bundle:
                build: ./oba/
                volumes:
                # poner el gtfs en oba/bundle
                        - ./oba/bundle:/bundle
                        - ./buenosaires:/data
                command: ["sh", "-c", "cd /bundle && java -Xss10m -Xmx10G -jar /app/onebusaway-transit-data-federation-builder-2.0.0-withAllDependencies.jar /data/colectivos.zip ."]

        oba:
                depends_on:
                        - postgres
                container_name: oba-ba
                image: onebusaway-ba:dev
                build: ./oba/
                volumes:
                        - ./oba/bundle:/bundle                                               
                ports:
                        - 8888:8080